### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wangqingpen** [claying/GCKN#1]
where    function   pooling_cpu  in  GCKN/gckn/dynamic_pooling

**Comment by claying** [comment]
Hi @wangqingpen,

Did you follow the installation section to install GCKN? 
Specifically, you need to compile the cpp and cuda files by running `python setup_torch.py build_ext --inplace`, which is defined in the Makefile (so just simply run `make .`).
The module `pooling_cpu` is defined in `setup_torch.py` file:
https://github.com/claying/GCKN/blob/e70b854a7ead00efd11e2c217f23ff95f5d96976/setup_torch.py#L21

**Comment by wangqingpen** [comment]
> Hi @wangqingpen,
> 
> Did you follow the installation section to install GCKN?
> Specifically, you need to compile the cpp and cuda files by running `python setup_torch.py build_ext --inplace`, which is defined in the Makefile (so just simply run `make .`).
> The module `pooling_cpu` is defined in `setup_torch.py` file:
> https://github.com/claying/GCKN/blob/e70b854a7ead00efd11e2c217f23ff95f5d96976/setup_torch.py#L21

Please tell me how to install the cyanure in Windows 10 pycharm. I have found many ways to install it, but I can't .thank you .

**Comment by claying** [comment]
> > Hi @wangqingpen,
> > Did you follow the installation section to install GCKN?
> > Specifically, you need to compile the cpp and cuda files by running `python setup_torch.py build_ext --inplace`, which is defined in the Makefile (so just simply run `make .`).
> > The module `pooling_cpu` is defined in `setup_torch.py` file:
> > https://github.com/claying/GCKN/blob/e70b854a7ead00efd11e2c217f23ff95f5d96976/setup_torch.py#L21
> 
> Please tell me how to install the cyanure in Windows 10 pycharm. I have found many ways to install it, but I can't .thank you .

I think cyanure is not supported on Windows yet, nor GCKN. I would recommend you to install GCKN on Linux or Mac OS, where I have tested GCKN to work successfully.
