### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ha-lins** [claying/GCKN#2]
Hi @claying,

Thanks for your released code! When I finished the installation and `make` and ran the code then, I recieved the following error message. 

```
 python main_unsup.py --dataset MUTAG --path-size 3 1 --sigma 1.5 1.5 --hidden-size 32 32 --aggregation
Traceback (most recent call last):
  File "main_unsup.py", line 6, in <module>
    from gckn.models import GCKNetFeature
  File "/data4/linshuai/GCKN/gckn/models.py", line 4, in <module>
    from .layers import PathLayer, NodePooling, Linear
  File "/data4/linshuai/GCKN/gckn/layers.py", line 10, in <module>
    from .path_conv_agg import path_conv_agg
  File "/data4/linshuai/GCKN/gckn/path_conv_agg.py", line 3, in <module>
    from gckn.gckn_fast.gckn_fast import path_conv_forward, path_conv_backward
  File "/data4/linshuai/GCKN/gckn/gckn_fast/gckn_fast.py", line 5, in <module>
    from gckn.gckn_fast import gckn_fast_cpu
ImportError: /data4/linshuai/GCKN/gckn/gckn_fast/gckn_fast_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv
```
It seems that `gckn_fast_cpu.cpython-36m-x86_64-linux-gnu.so` was generated automatically. If I removed it, the error message
became: 
```
  File "/data4/linshuai/GCKN/gckn/gckn_fast/gckn_fast.py", line 5, in <module>
    from gckn.gckn_fast import gckn_fast_cpu
ImportError: cannot import name 'gckn_fast_cpu'
```
What's the requirement of `cuda`? My `cuda` version is `10.1` and pytorch version is `1.3.1`.  Could you pls help me with it?

Thanks in advance!

**Comment by ha-lins** [comment]
`Update:`
I changed a machine and it can work well. However, the reproduced results are much lower than those reported in the paper.  For example, for  `GCKN-subtree` on the `IMDBBINARY` dataset, the reported results are `77.8` while my reproduced ones are
```
               C     train   test  test_std
0       0.000100  0.699222  0.692  0.053254
1       0.000137  0.705556  0.690  0.061806
2       0.000187  0.713000  0.693  0.055866
3       0.000255  0.713333  0.705  0.055000
4       0.000349  0.714222  0.711  0.046357
5       0.000476  0.716667  0.712  0.047074
6       0.000651  0.716667  0.709  0.053376
7       0.000890  0.718889  0.707  0.047339
8       0.001215  0.722222  0.709  0.047000
9       0.001661  0.726222  0.712  0.046433
10      0.002270  0.728111  0.714  0.045869
11      0.003101  0.729889  0.721  0.048052
12      0.004238  0.732000  0.723  0.045618
13      0.005790  0.731111  0.722  0.043081
14      0.007912  0.734222  0.728  0.038158
15      0.010812  0.735556  0.730  0.041231
16      0.014774  0.737889  0.731  0.038328
17      0.020188  0.739333  0.734  0.038523
18      0.027585  0.739222  0.732  0.039446
19      0.037694  0.739333  0.730  0.040743
20      0.051507  0.740000  0.734  0.040546
21      0.070381  0.740667  0.733  0.041725
22      0.096172  0.741333  0.734  0.042237
23      0.131415  0.743000  0.732  0.044000
24      0.179571  0.741333  0.735  0.034132
25      0.245375  0.742111  0.729  0.041581
26      0.335292  0.743111  0.735  0.032016
27      0.458160  0.743111  0.733  0.034366
28      0.626052  0.742778  0.734  0.031369
29      0.855467  0.743111  0.732  0.030265
30      1.168952  0.743667  0.734  0.032619
31      1.597312  0.745889  0.733  0.027946
32      2.182645  0.745222  0.736  0.032924
33      2.982471  0.742333  0.728  0.043313
34      4.075393  0.745778  0.735  0.036125
35      5.568814  0.746556  0.733  0.027586
36      7.609497  0.746556  0.733  0.032573
37     10.397984  0.747556  0.734  0.038262
38     14.208308  0.747111  0.738  0.031875
39     19.414919  0.746556  0.737  0.030676
40     26.529485  0.745778  0.733  0.036069
41     36.251170  0.750111  0.736  0.033526
42     49.535352  0.748778  0.730  0.034351
43     67.687500  0.749111  0.732  0.037094
44     92.491473  0.747333  0.735  0.030741
45    126.384820  0.744222  0.736  0.036661
46    172.698329  0.746222  0.731  0.036455
47    235.983347  0.744889  0.734  0.035833
48    322.459055  0.744889  0.734  0.035833
49    440.623643  0.744889  0.734  0.035833
50    602.089449  0.744889  0.734  0.035833
51    822.724134  0.745111  0.734  0.035833
52   1124.210035  0.745111  0.734  0.035833
53   1536.174947  0.745111  0.734  0.035833
54   2099.103720  0.745111  0.734  0.035833
55   2868.316813  0.745111  0.734  0.035833
56   3919.406775  0.745111  0.734  0.035833
57   5355.666918  0.745111  0.734  0.035833
58   7318.242219  0.745111  0.734  0.035833
59  10000.000000  0.745111  0.734  0.035833
```
Do you have any advice for tuning parameters? Thanks!

**Comment by claying** [comment]
Hi @ha-lins 

Thanks for your interest in our work.
Since the benchmark datasets are relatively small, you will need to follow the grid search listed in our paper to reproduce the results. For instance, the best score for IMDBBINARY on my machine was obtained with a relatively large path size using the following command:
`python main_unsup.py --dataset IMDBBINARY --path-size 5 1 --sigma 0.3 0.3 --hidden-size 512 512 --global-pooling mean --pooling sum --aggregation`

**Comment by ha-lins** [comment]
Thanks for your reply! @claying 

Could you pls give the hyperparameters used in other datasets, such as `MUTAG`? I've tried searching the hyperparameters while it's hard to reproduce the `MUTAG` results.

**Comment by wangqingpen** [comment]
> 嗨@claying，
> 
> 感谢您发布的代码！当我完成安装并`make`运行代码之后，我收到以下错误消息。
> 
> ```
>  python main_unsup.py --dataset MUTAG --path-size 3 1 --sigma 1.5 1.5 --hidden-size 32 32 --aggregation
> Traceback (most recent call last):
>   File "main_unsup.py", line 6, in <module>
>     from gckn.models import GCKNetFeature
>   File "/data4/linshuai/GCKN/gckn/models.py", line 4, in <module>
>     from .layers import PathLayer, NodePooling, Linear
>   File "/data4/linshuai/GCKN/gckn/layers.py", line 10, in <module>
>     from .path_conv_agg import path_conv_agg
>   File "/data4/linshuai/GCKN/gckn/path_conv_agg.py", line 3, in <module>
>     from gckn.gckn_fast.gckn_fast import path_conv_forward, path_conv_backward
>   File "/data4/linshuai/GCKN/gckn/gckn_fast/gckn_fast.py", line 5, in <module>
>     from gckn.gckn_fast import gckn_fast_cpu
> ImportError: /data4/linshuai/GCKN/gckn/gckn_fast/gckn_fast_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv
> ```
> 
> 似乎`gckn_fast_cpu.cpython-36m-x86_64-linux-gnu.so`是自动生成的。如果删除它，错误消息将
> 变为：
> 
> ```
>   File "/data4/linshuai/GCKN/gckn/gckn_fast/gckn_fast.py", line 5, in <module>
>     from gckn.gckn_fast import gckn_fast_cpu
> ImportError: cannot import name 'gckn_fast_cpu'
> ```
> 
> 有什么要求`cuda`？我的`cuda`版本是，`10.1`而pytorch版本是`1.3.1`。您能帮我吗？
> 
> 提前致谢！

**Comment by wangqingpen** [comment]
I also have this problem. How do you solve this problem? Thank you


> Hi @claying,
> 
> Thanks for your released code! When I finished the installation and `make` and ran the code then, I recieved the following error message.
> 
> ```
>  python main_unsup.py --dataset MUTAG --path-size 3 1 --sigma 1.5 1.5 --hidden-size 32 32 --aggregation
> Traceback (most recent call last):
>   File "main_unsup.py", line 6, in <module>
>     from gckn.models import GCKNetFeature
>   File "/data4/linshuai/GCKN/gckn/models.py", line 4, in <module>
>     from .layers import PathLayer, NodePooling, Linear
>   File "/data4/linshuai/GCKN/gckn/layers.py", line 10, in <module>
>     from .path_conv_agg import path_conv_agg
>   File "/data4/linshuai/GCKN/gckn/path_conv_agg.py", line 3, in <module>
>     from gckn.gckn_fast.gckn_fast import path_conv_forward, path_conv_backward
>   File "/data4/linshuai/GCKN/gckn/gckn_fast/gckn_fast.py", line 5, in <module>
>     from gckn.gckn_fast import gckn_fast_cpu
> ImportError: /data4/linshuai/GCKN/gckn/gckn_fast/gckn_fast_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv
> ```
> 
> It seems that `gckn_fast_cpu.cpython-36m-x86_64-linux-gnu.so` was generated automatically. If I removed it, the error message
> became:
> 
> ```
>   File "/data4/linshuai/GCKN/gckn/gckn_fast/gckn_fast.py", line 5, in <module>
>     from gckn.gckn_fast import gckn_fast_cpu
> ImportError: cannot import name 'gckn_fast_cpu'
> ```
> 
> What's the requirement of `cuda`? My `cuda` version is `10.1` and pytorch version is `1.3.1`. Could you pls help me with it?
> 
> Thanks in advance!

**### I also have this problem. How do you solve this problem? Thank you**
